# Generated by Django 3.0.2 on 2020-01-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
