# Generated by Django 3.0.2 on 2020-01-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0002_auto_20200121_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(default='2000-01-01 12:00:00'),
        ),
    ]
