# Generated by Django 3.0.2 on 2020-01-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var_data',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='var_data',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
    ]
